name: CI
on: [push]
jobs:
  deploy:
   if: github.ref == 'refs/heads/New-Branch'
   runs-on: [ubuntu-latest]
   steps:
     - uses: actions/checkout@v1
     - name: Push to server
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.ip }}
          username: ${{ secrets.uname }}
          password: ${{ secrets.pass }}
          script: ls -la
     
