name: deployproject

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.sshkey }}
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.ip }}
          REMOTE_USER: ${{ secrets.uname }}
          TARGET: ${{ secrets.target}}
     
